// One entry per life chapter. `bg` is the PixelLab background image key
// (assets/bg/<id>.png); if it's missing, the procedural placeholder
// (sky gradient + `skyline` silhouettes) is drawn instead.
export const CHAPTERS = [
  {
    id: 'born',
    year: 'Day 1',
    title: 'Born in Thailand',
    caption: 'Born in Bangkok, Thailand.',
    sky: [0xffb36b, 0xffe2a8],
    ground: 0x8a5a2b,
    skyline: 'temple',
    length: 1100,
    age: 'toddler',
    pickup: 'mango',
  },
  {
    id: 'flight',
    year: 'Age 2',
    title: 'Off to America',
    caption: 'At age 2, my family moved to the United States.',
    sky: [0x4aa3ff, 0xbfe6ff],
    ground: 0xffffff,
    skyline: 'clouds',
    length: 1300,
    age: 'toddler',
    pickup: 'star',
    clouds: true,
  },
  {
    id: 'umd',
    year: '1990s',
    title: 'University of Maryland',
    caption: 'B.S. Computer Science at the University of Maryland — with a minor in Theatre Performance.',
    sky: [0x6fb7ff, 0xd9f0ff],
    ground: 0x4d8b3a,
    skyline: 'campus',
    length: 1600,
    age: 'student',
    pickup: 'floppy',
  },
  {
    id: 'early',
    year: '1999–2005',
    title: 'First Jobs',
    caption: 'Device drivers in Maryland, web apps in Chicago, then my first startup: Affective Media.',
    sky: [0x2b3a67, 0x8892c9],
    ground: 0x55555f,
    skyline: 'chicago',
    length: 1700,
    age: 'adult',
    pickup: 'floppy',
  },
  {
    id: 'sf',
    year: '2006',
    title: '2nd Rate Geniuses',
    caption: 'Co-founded 2nd Rate Geniuses in San Francisco, building products for startups for 7 years.',
    sky: [0xff8a5b, 0xffd39b],
    ground: 0x7a6a5a,
    skyline: 'sf',
    length: 1800,
    age: 'adult',
    pickup: 'coffee',
  },
  {
    id: 'github',
    year: '2013',
    title: 'GitHub',
    caption: 'Joined GitHub and founded the billing & payments team.',
    sky: [0x24292e, 0x586069],
    ground: 0x2f363d,
    skyline: 'office',
    length: 1800,
    age: 'adult',
    pickup: 'commit',
  },
  {
    id: 'camp',
    year: '2015',
    title: "Steve & Kate's Camp",
    caption: "Head of Engineering at Steve & Kate's Camp, building tech for 40+ summer camps.",
    sky: [0x7fd3ff, 0xe8fbff],
    ground: 0x5fa83a,
    skyline: 'camp',
    length: 1700,
    age: 'adult',
    pickup: 'star',
  },
  {
    id: 'omg',
    year: '2018',
    title: 'Back to Bangkok',
    caption: 'Moved back to Bangkok. CTO of OMG Network, scaling Ethereum.',
    sky: [0x1b1040, 0x6a3fa0],
    ground: 0x3a2f5a,
    skyline: 'bangkok',
    length: 1800,
    age: 'adult',
    pickup: 'block',
  },
  {
    id: 'typhoon',
    year: '2021',
    title: 'SCB 10X & Typhoon',
    caption: "Joined SCB 10X and founded Typhoon, Thailand's open-source frontier AI lab.",
    sky: [0x3b2a7a, 0x9d7be0],
    ground: 0x4a3b8a,
    skyline: 'bangkok',
    length: 2000,
    age: 'adult',
    pickup: 'paper',
  },
  {
    id: 'gulf',
    year: '2026',
    title: 'Gulf',
    caption: 'Now at Gulf. To be continued…',
    sky: [0x0f4c81, 0x7cc4ff],
    ground: 0x24507a,
    skyline: 'bangkok',
    length: 900,
    age: 'adult',
    pickup: 'star',
  },
];
